#!/usr/bin/env node
const {exec}=require('child_process');
exec(`xprop -id $(xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5) WM_NAME | cut -d '"' -f 2`,(e,s,se)=>{
  console.log(s.replace(/\n.*$/, ''));
});
