#!/usr/bin/env node
const {execSync}=require('child_process'),{exec}=require('child_process'),format=require('./lib/format');
var b=process.env.BLOCK_INSTANCE;
exec(`test ! -f /tmp/.bandwidth && echo 0 0 > /tmp/.bandwidth `);
if (!b) {
  b=execSync(`echo $(ip route get 1.0.0.1 | grep -Po '(?<=(dev )).*(?= src)')`).toString('utf8').replace(/\n.*$/, '');
}
const x=execSync(`echo $(grep '`+b+`' /proc/net/dev | awk -F: '{print  $2}' | awk '{print $1" "$9}')`).toString('utf8').replace(/\n.*$/, '').split(' ');
const p=execSync(`cat /tmp/.bandwidth`).toString('utf8').replace(/\n.*$/, '').split(',')[0].split(' ');
exec(`echo "`+ x.join(' ') +`" > /tmp/.bandwidth`);
console.log(' '+format((x[0]-p[0]),2),' '+format((x[1]-p[1]),2));
