#!/usr/bin/env node
const {execSync}=require('child_process');
const {exec}=require('child_process');
var b=process.env.BLOCK_INSTANCE;
if (!b) {
  b=execSync(`echo $(ip route get 1.0.0.1 | grep -Po '(?<=(dev )).*(?= src)')`).toString('utf8').replace(/\n.*$/, '');
}
const x=execSync(`echo $(grep '`+b+`' /proc/net/dev | awk -F: '{print  $2}' | awk '{print $1" "$9}')`).toString('utf8').replace(/\n.*$/, '').split(' ');
const p=execSync(`cat /tmp/.bandwidth`).toString('utf8').replace(/\n.*$/, '').split(',')[0].split(' ');
exec(`echo "`+ x.join(' ') +`" > /tmp/.bandwidth`);
function format(bytes,d) {
  if(bytes < 1024) return bytes + " b";
  else if(bytes < 1048576) return(bytes / 1024).toFixed(0) + " kb";
  else if(bytes < 1073741824) return(bytes / 1048576).toFixed(2) + " mb";
  else return(bytes / 1073741824).toFixed(2) + " gb";
}

console.log(' '+format((x[0]-p[0]),2),' '+format((x[1]-p[1]),2));
