#!/usr/bin/env node
const {execSync}=require('child_process');
var b=process.env.BLOCK_INSTANCE.split(';');
for (var i = 0; i < b.length; i++) {
  if (b[i]!==''&&execSync(`xset -q|grep LED| awk '{ print $10 }'`).toString('utf8').replace(/\n.*$/, '')==b[i].split(',')[1]) {
    console.log(b[i].split(',')[0]);
  }
}
